-- 1. Alle benötigten Datenbanken anlegen
CREATE DATABASE prefect;
CREATE DATABASE mlflow;
CREATE DATABASE fraud_detection;

-- Change to the fraud detection 
\c fraud_detection

-- Create the new table transactions in the fraud detection database
CREATE TABLE IF NOT EXISTS public.transactions (
    elapsed_sec FLOAT,
    V1 DOUBLE PRECISION NOT NULL,
    pc_2 DOUBLE PRECISION NOT NULL,
    pc_3 DOUBLE PRECISION NOT NULL,
    pc_4 DOUBLE PRECISION NOT NULL,
    pc_5 DOUBLE PRECISION NOT NULL,
    pc_6 DOUBLE PRECISION NOT NULL,
    pc_7 DOUBLE PRECISION NOT NULL,
    pc_8 DOUBLE PRECISION NOT NULL,
    pc_9 DOUBLE PRECISION NOT NULL,
    pc_10 DOUBLE PRECISION NOT NULL,
    pc_11 DOUBLE PRECISION NOT NULL,
    pc_12 DOUBLE PRECISION NOT NULL,
    pc_13 DOUBLE PRECISION NOT NULL,
    pc_14 DOUBLE PRECISION NOT NULL,
    pc_15 DOUBLE PRECISION NOT NULL,
    pc_16 DOUBLE PRECISION NOT NULL,
    pc_17 DOUBLE PRECISION NOT NULL,
    pc_18 DOUBLE PRECISION NOT NULL,
    pc_19 DOUBLE PRECISION NOT NULL,
    pc_20 DOUBLE PRECISION NOT NULL,
    pc_21 DOUBLE PRECISION NOT NULL,
    pc_22 DOUBLE PRECISION NOT NULL,
    pc_23 DOUBLE PRECISION NOT NULL,
    pc_24 DOUBLE PRECISION NOT NULL,
    pc_25 DOUBLE PRECISION NOT NULL,
    pc_26 DOUBLE PRECISION NOT NULL,
    pc_27 DOUBLE PRECISION NOT NULL,
    pc_28 DOUBLE PRECISION NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    class INT,
    ingestion_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);