-- 1. Alle benötigten Datenbanken anlegen
CREATE DATABASE prefect;
CREATE DATABASE mlflow;
CREATE DATABASE fraud_detection;

-- Change to the fraud detection 
\c fraud_detection

-- Create a new schema
CREATE SCHEMA IF NOT EXISTS raw;

-- Create the new table transactions in the fraud detection database
CREATE TABLE IF NOT EXISTS raw.transactions (
    "Time" FLOAT,
    "V1" DOUBLE PRECISION NOT NULL,
    "V2" DOUBLE PRECISION NOT NULL,
    "V3" DOUBLE PRECISION NOT NULL,
    "V4" DOUBLE PRECISION NOT NULL,
    "V5" DOUBLE PRECISION NOT NULL,
    "V6" DOUBLE PRECISION NOT NULL,
    "V7" DOUBLE PRECISION NOT NULL,
    "V8" DOUBLE PRECISION NOT NULL,
    "V9" DOUBLE PRECISION NOT NULL,
    "V10" DOUBLE PRECISION NOT NULL,
    "V11" DOUBLE PRECISION NOT NULL,
    "V12" DOUBLE PRECISION NOT NULL,
    "V13" DOUBLE PRECISION NOT NULL,
    "V14" DOUBLE PRECISION NOT NULL,
    "V15" DOUBLE PRECISION NOT NULL,
    "V16" DOUBLE PRECISION NOT NULL,
    "V17" DOUBLE PRECISION NOT NULL,
    "V18" DOUBLE PRECISION NOT NULL,
    "V19" DOUBLE PRECISION NOT NULL,
    "V20" DOUBLE PRECISION NOT NULL,
    "V21" DOUBLE PRECISION NOT NULL,
    "V22" DOUBLE PRECISION NOT NULL,
    "V23" DOUBLE PRECISION NOT NULL,
    "V24" DOUBLE PRECISION NOT NULL,
    "V25" DOUBLE PRECISION NOT NULL,
    "V26" DOUBLE PRECISION NOT NULL,
    "V27" DOUBLE PRECISION NOT NULL,
    "V28" DOUBLE PRECISION NOT NULL,
    "Amount" DOUBLE PRECISION NOT NULL,
    "Class" INT,
    "ingestion_time" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create the new table transactions in the fraud detection database
CREATE TABLE IF NOT EXISTS raw.labeled_predictions_queue (
    "Time" FLOAT,
    "V1" DOUBLE PRECISION NOT NULL,
    "V2" DOUBLE PRECISION NOT NULL,
    "V3" DOUBLE PRECISION NOT NULL,
    "V4" DOUBLE PRECISION NOT NULL,
    "V5" DOUBLE PRECISION NOT NULL,
    "V6" DOUBLE PRECISION NOT NULL,
    "V7" DOUBLE PRECISION NOT NULL,
    "V8" DOUBLE PRECISION NOT NULL,
    "V9" DOUBLE PRECISION NOT NULL,
    "V10" DOUBLE PRECISION NOT NULL,
    "V11" DOUBLE PRECISION NOT NULL,
    "V12" DOUBLE PRECISION NOT NULL,
    "V13" DOUBLE PRECISION NOT NULL,
    "V14" DOUBLE PRECISION NOT NULL,
    "V15" DOUBLE PRECISION NOT NULL,
    "V16" DOUBLE PRECISION NOT NULL,
    "V17" DOUBLE PRECISION NOT NULL,
    "V18" DOUBLE PRECISION NOT NULL,
    "V19" DOUBLE PRECISION NOT NULL,
    "V20" DOUBLE PRECISION NOT NULL,
    "V21" DOUBLE PRECISION NOT NULL,
    "V22" DOUBLE PRECISION NOT NULL,
    "V23" DOUBLE PRECISION NOT NULL,
    "V24" DOUBLE PRECISION NOT NULL,
    "V25" DOUBLE PRECISION NOT NULL,
    "V26" DOUBLE PRECISION NOT NULL,
    "V27" DOUBLE PRECISION NOT NULL,
    "V28" DOUBLE PRECISION NOT NULL,
    "Amount" DOUBLE PRECISION NOT NULL,
    "prediction" INT,
    "Class" INT,
    "ingestion_time" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create the new table transactions in the fraud detection database
CREATE TABLE IF NOT EXISTS raw.predictions (
    "Time" FLOAT,
    "V1" DOUBLE PRECISION NOT NULL,
    "V2" DOUBLE PRECISION NOT NULL,
    "V3" DOUBLE PRECISION NOT NULL,
    "V4" DOUBLE PRECISION NOT NULL,
    "V5" DOUBLE PRECISION NOT NULL,
    "V6" DOUBLE PRECISION NOT NULL,
    "V7" DOUBLE PRECISION NOT NULL,
    "V8" DOUBLE PRECISION NOT NULL,
    "V9" DOUBLE PRECISION NOT NULL,
    "V10" DOUBLE PRECISION NOT NULL,
    "V11" DOUBLE PRECISION NOT NULL,
    "V12" DOUBLE PRECISION NOT NULL,
    "V13" DOUBLE PRECISION NOT NULL,
    "V14" DOUBLE PRECISION NOT NULL,
    "V15" DOUBLE PRECISION NOT NULL,
    "V16" DOUBLE PRECISION NOT NULL,
    "V17" DOUBLE PRECISION NOT NULL,
    "V18" DOUBLE PRECISION NOT NULL,
    "V19" DOUBLE PRECISION NOT NULL,
    "V20" DOUBLE PRECISION NOT NULL,
    "V21" DOUBLE PRECISION NOT NULL,
    "V22" DOUBLE PRECISION NOT NULL,
    "V23" DOUBLE PRECISION NOT NULL,
    "V24" DOUBLE PRECISION NOT NULL,
    "V25" DOUBLE PRECISION NOT NULL,
    "V26" DOUBLE PRECISION NOT NULL,
    "V27" DOUBLE PRECISION NOT NULL,
    "V28" DOUBLE PRECISION NOT NULL,
    "Amount" DOUBLE PRECISION NOT NULL,
    "prediction" INT,
    "ingestion_time" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);