name: Linting, Formatting & Code Quality

on:
  push:
  pull_request:

jobs:
  ruff-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install & Run Ruff
        run: |
          pip install ruff
          ruff -v check .
          ruff format --check .